services:
  dev:
    build:
      context: . 
      dockerfile: docker/Dockerfile.php82
      target: dev-envs
    ports:
      - '8080:80'
    volumes:
      - ./config_local.php:/app/config_local.php
      - ./lib:/app/lib
      - ./test:/app/test
